FROM ubuntu:20.04

WORKDIR /app
COPY logs.txt .
ENV FRONT_URL=http://localhost:5000

RUN apt-get update && apt-get install -y curl && apt-get install -y git
RUN curl -sL https://deb.nodesource.com/setup_10.x | bash && apt install -y nodejs
RUN node -v && npm -v
RUN git clone https://github.com/docker-hy/backend-example-docker.git
CMD cd backend-example-docker && npm install && npm start
